name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: 사용버전?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
      
  - type: dropdown
    id: apptype
    attributes:
      label: App type
      multiple: true
      options:
        - Store App
        - User App

  - type: dropdown
    id: ostype
    attributes:
      label: OS type
      multiple: true
      options:
        - Android
        - iOS

  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: 재현을 위한 사전조건및 재현에 이르기까지의 과정과 이슈내용
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
